version: '3.8'
services:
  app:
    build: 
      dockerfile: ./app.Dockerfile
      context: ./
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      API_MOCK_URL: "${API_MOCK_URL}"
      CLIENT_ID: "${CLIENT_ID}"
      CLIENT_SECRET: "${CLIENT_SECRET}"
      TOKEN_EXPIRATION_SECONDS: "${TOKEN_EXPIRATION_SECONDS}"
      DATABASE_URL: "${DATABASE_URL}"
    depends_on:
      - redis
      - db
    restart: always

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always

  db:
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  pgdata: